# Generated by Django 5.2.1 on 2026-03-02 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=200)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('witty', 'Witty'), ('formal', 'Formal'), ('persuasive', 'Persuasive')], default='professional', max_length=50)),
                ('audience', models.TextField(help_text='Describe your target audience')),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('product_description', 'Product Description'), ('ad_copy', 'Ad Copy'), ('email_sequence', 'Email Sequence')], max_length=50)),
                ('prompt_extra', models.TextField(blank=True, help_text='Extra instructions')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('result_text', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='content.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('words_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'created_at'], name='content_pro_user_id_766348_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgeneration',
            index=models.Index(fields=['user', 'status'], name='content_con_user_id_789552_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgeneration',
            index=models.Index(fields=['project', 'created_at'], name='content_con_project_37fcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='usageledger',
            index=models.Index(fields=['user', 'year', 'month'], name='content_usa_user_id_e05cd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usageledger',
            unique_together={('user', 'year', 'month')},
        ),
    ]
