# Generated by Django 5.2.1 on 2026-03-02 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('generation_created', 'Generation Created'), ('generation_success', 'Generation Success'), ('generation_failed', 'Generation Failed'), ('subscription_activated', 'Subscription Activated'), ('subscription_cancelled', 'Subscription Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('quota_exceeded', 'Quota Exceeded')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='analytics_a_user_id_6117db_idx'), models.Index(fields=['created_at'], name='analytics_a_created_294085_idx')],
            },
        ),
    ]
